name: ML CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Train model
        run: |
          python train.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            output/model
            output/results/metrics.json

  deploy:
    needs: train
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: model-artifacts

      - name: Install system tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq bc

      - name: Read metrics
        run: |
          echo "R2=$(jq -r '.r2' output/results/metrics.json)" >> $GITHUB_ENV
          echo "MSE=$(jq -r '.mse' output/results/metrics.json)" >> $GITHUB_ENV

      - name: Debug metrics
        run: |
          echo "Current R2: $R2"
          echo "Current MSE: $MSE"
          echo "Best R2: ${{ vars.BEST_R2 }}"
          echo "Best MSE: ${{ vars.BEST_MSE }}"

      - name: Compare metrics
        run: |
          better_r2=$(echo "$R2 > ${{ vars.BEST_R2 }}" | bc -l)
          better_mse=$(echo "$MSE < ${{ vars.BEST_MSE }}" | bc -l)

          if [ "$better_r2" -eq 0 ] && [ "$better_mse" -eq 0 ]; then
            echo "2022BCS0109 ---- Metric did not improve"
            exit 0
          fi

      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Debug workspace
        run: |
          pwd
          ls -la
          find . -name Dockerfile

      - name: Build Docker image
        run: |
          docker build -f DockerFile -t ${{ secrets.DOCKER_USERNAME }}/wine_predict:${{ github.run_number }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/wine_predict:${{ github.run_number }}

      - name: Update best metrics
        run: |
          gh variable set BEST_R2 --value "$R2"
          gh variable set BEST_MSE --value "$MSE"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
